-- Initial schema setup

--Execute with SYSDBA user
--ALTER DATABASE SET TIME_ZONE = 'Europe/Bucharest';
create user webapp identified by parola01;
grant create session to webapp;

GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO webapp;
grant create any context to webapp;
GRANT UNLIMITED TABLESPACE TO webapp;
ALTER USER WEBAPP DEFAULT TABLESPACE USERS;
grant execute on dbms_lock to webapp;

--Execute with WEBAPP user
create or replace package webapp.DATABSE_CONNECTION_CONTEXT is
    procedure set_connection_context (p_username in varchar2);
end;
/
create or replace package body webapp.DATABSE_CONNECTION_CONTEXT is
    procedure set_connection_context (p_username in varchar2) is
    begin
        DBMS_SESSION.set_context(namespace => 'WEBAPP_CTX', attribute => 'USERNAME', value => p_username);
    end set_connection_context;
end;
/

CREATE CONTEXT WEBAPP_CTX USING webapp.DATABSE_CONNECTION_CONTEXT;
grant execute on Dbms_Session to webapp;
grant execute on webapp.DATABSE_CONNECTION_CONTEXT to webapp;

-- Create table
create table WEBAPP.USER_APP
(
    id          NUMBER generated by default on null as identity,
    username    VARCHAR2(255) not null,
    first_name  VARCHAR2(255) not null,
    last_name   VARCHAR2(255) not null,
    inserted_at TIMESTAMP(6) WITH TIME ZONE default SYSTIMESTAMP not null,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    version     NUMBER
)
    tablespace USERS
    pctfree 10
    initrans 1
    maxtrans 255;
-- Create/Recreate primary, unique and foreign key constraints
alter table WEBAPP.USER_APP
    add constraint PK_USERS primary key (ID)
        using index
            tablespace USERS
            pctfree 10
            initrans 2
            maxtrans 255;
alter table WEBAPP.USER_APP
    add unique (USERNAME)
        using index
            tablespace USERS
            pctfree 10
            initrans 2
            maxtrans 255;

-- Create table
create table WEBAPP.USER_PROFILES
(
    id           NUMBER generated by default on null as identity,
    id_user      NUMBER not null,
    profile_name VARCHAR2(255) not null,
    inserted_at  TIMESTAMP(6) WITH TIME ZONE default SYSTIMESTAMP not null,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    version      NUMBER
)
    tablespace USERS
    pctfree 10
    initrans 1
    maxtrans 255;
-- Create/Recreate indexes
create index WEBAPP.IDX_USER_PROFILES_USER on WEBAPP.USER_PROFILES (ID_USER)
    tablespace USERS
    pctfree 10
    initrans 2
    maxtrans 255;
-- Create/Recreate primary, unique and foreign key constraints
alter table WEBAPP.USER_PROFILES
    add constraint PK_USER_PROFILES primary key (ID)
        using index
            tablespace USERS
            pctfree 10
            initrans 2
            maxtrans 255;
alter table WEBAPP.USER_PROFILES
    add constraint FK_USER_PROFILES_USER foreign key (ID_USER)
        references WEBAPP.USER_APP (ID);

-- Adăugarea unei constrângeri de cheie primară pentru coloana ID
-- Create table
create table WEBAPP.USER_ACTIVE_PROFILES
(
    id           NUMBER generated by default on null as identity,
    id_user      NUMBER not null,
    username     VARCHAR2(255) not null,
    id_profile   NUMBER not null,
    profile_name VARCHAR2(255) not null,
    inserted_at  TIMESTAMP(6) WITH TIME ZONE default SYSTIMESTAMP not null,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    version      NUMBER
)
    tablespace USERS
    pctfree 10
    initrans 1
    maxtrans 255;
-- Create/Recreate primary, unique and foreign key constraints
alter table WEBAPP.USER_ACTIVE_PROFILES
    add constraint PK_USER_ACTIVE_PROFILES primary key (ID)
        using index
            tablespace USERS
            pctfree 10
            initrans 2
            maxtrans 255;

-- Create table
create table WEBAPP.USER_ROLES
(
    id           NUMBER generated by default on null as identity,
    id_user      NUMBER not null,
    role_name VARCHAR2(255) not null,
    inserted_at  TIMESTAMP(6) WITH TIME ZONE default SYSTIMESTAMP not null,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    version      NUMBER
)
    tablespace USERS
    pctfree 10
    initrans 1
    maxtrans 255;
-- Create/Recreate indexes
create index IDX_USER_ROLES_USER on USER_ROLES (ID_USER)
    tablespace USERS
    pctfree 10
    initrans 2
    maxtrans 255;
-- Create/Recreate primary, unique and foreign key constraints
alter table WEBAPP.USER_ROLES
    add constraint PK_USER_ROLES primary key (ID)
        using index
            tablespace USERS
            pctfree 10
            initrans 2
            maxtrans 255;
alter table WEBAPP.USER_ROLES
    add constraint FK_USER_ROLES_USER foreign key (ID_USER)
        references USER_APP (ID);

grant select, insert, update on webapp.user_app to webapp;
grant select, insert, update on webapp.user_profiles to webapp;
grant select, insert, update on webapp.user_roles to webapp;

CREATE OR REPLACE TRIGGER webapp.trg_user_app_updated_at
    BEFORE UPDATE ON webapp.user_app
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER webapp.trg_user_profiles_updated_at
    BEFORE UPDATE ON webapp.user_profiles
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER webapp.trg_user_roles_updated_at
    BEFORE UPDATE ON webapp.user_roles
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/
alter table webapp.USER_ACTIVE_PROFILES
    add constraint UQ_UAP_USERNAME unique (USERNAME);

create table webapp.USER_NOTIFICATIONS_NEW
(
    id                      NUMBER generated by default on null as identity,
    id_profile              NUMBER not null,
    module_name             VARCHAR2(255) not null,
    module_aggregate_id     NUMBER not null,
    inserted_at             TIMESTAMP(6) WITH TIME ZONE default SYSTIMESTAMP not null,
    updated_at              TIMESTAMP(6) WITH TIME ZONE,
    version                 NUMBER
)
    tablespace USERS
    pctfree 10
    initrans 1
    maxtrans 255
    storage
(
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
);
-- Create/Recreate primary, unique and foreign key constraints
alter table webapp.USER_NOTIFICATIONS_NEW
    add constraint PK_USER_NOTIFICATIONS_NEW primary key (ID)
        using index
            tablespace USERS
            pctfree 10
            initrans 2
            maxtrans 255
            storage
            (
            initial 64K
            next 1M
            minextents 1
            maxextents unlimited
            );

create index IDX_PROFILE_USER_NOTIFICATIONS_NEW on webapp.USER_NOTIFICATIONS_NEW (id_profile)
    tablespace USERS
    pctfree 10
    initrans 2
    maxtrans 255
    storage
    (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
    );
alter table webapp.USER_NOTIFICATIONS_NEW
    add constraint FK_PROFILE_USER_NOTIFICATIONS_NEW foreign key (id_profile)
        references webapp.USER_PROFILES (ID);

create table webapp.USER_NOTIFICATIONS_OLD
(
    id                      NUMBER generated by default on null as identity,
    id_profile              NUMBER not null,
    module_name             VARCHAR2(255) not null,
    module_aggregate_id     NUMBER not null,
    inserted_at             TIMESTAMP(6) WITH TIME ZONE default SYSTIMESTAMP not null,
    updated_at              TIMESTAMP(6) WITH TIME ZONE,
    version                 NUMBER
)
    tablespace USERS
    pctfree 10
    initrans 1
    maxtrans 255
    storage
(
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
);
-- Create/Recreate primary, unique and foreign key constraints
alter table webapp.USER_NOTIFICATIONS_OLD
    add constraint PK_USER_NOTIFICATIONS_OLD primary key (ID)
        using index
            tablespace USERS
            pctfree 10
            initrans 2
            maxtrans 255
            storage
            (
            initial 64K
            next 1M
            minextents 1
            maxextents unlimited
            );

create index IDX_PROFILE_USER_NOTIFICATIONS_OLD on webapp.USER_NOTIFICATIONS_OLD (id_profile)
    tablespace USERS
    pctfree 10
    initrans 2
    maxtrans 255
    storage
    (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
    );


CREATE OR REPLACE PACKAGE WEBAPP.MESAJE_MODUL_A IS
    PROCEDURE verificare_mesaje (p_id_profile IN VARCHAR2);
END;
/
CREATE OR REPLACE PACKAGE BODY WEBAPP.MESAJE_MODUL_A IS
    PROCEDURE verificare_mesaje (p_id_profile IN VARCHAR2) IS
    BEGIN

        delete webapp.user_notifications_old t
        where t.module_name = 'MODUL_A' and
            t.id_profile = p_id_profile;

        --simulam durata unui select count in tabelul/tabelele aferente modulului A
        dbms_lock.sleep(3);

        FOR i in 1..10 loop
                insert into webapp.user_notifications_old
                (id_profile, module_name, module_aggregate_id)
                values
                    (p_id_profile, 'MODUL_A', 1);
            end loop;

    END verificare_mesaje;
END;
/

CREATE OR REPLACE PACKAGE WEBAPP.MESAJE_MODUL_B IS
    PROCEDURE verificare_mesaje (p_id_profile IN VARCHAR2);
END;
/
CREATE OR REPLACE PACKAGE BODY WEBAPP.MESAJE_MODUL_B IS
    PROCEDURE verificare_mesaje (p_id_profile IN VARCHAR2) IS
    BEGIN

        delete webapp.user_notifications_old t
        where t.module_name = 'MODUL_B' and
            t.id_profile = p_id_profile;

        --simulam durata unui select count in tabelul/tabelele aferente modulului A
        dbms_lock.sleep(6);

        FOR i in 1..15 loop
                insert into webapp.user_notifications_old
                (id_profile, module_name, module_aggregate_id)
                values
                    (p_id_profile, 'MODUL_B', 1);
            end loop;

    END verificare_mesaje;
END;
/

CREATE OR REPLACE PACKAGE WEBAPP.MESAJE_MODUL_C IS
    PROCEDURE verificare_mesaje (p_id_profile IN VARCHAR2);
END;
/
CREATE OR REPLACE PACKAGE BODY WEBAPP.MESAJE_MODUL_C IS
    PROCEDURE verificare_mesaje (p_id_profile IN VARCHAR2) IS
    BEGIN

        delete webapp.user_notifications_old t
        where t.module_name = 'MODUL_C' and
            t.id_profile = p_id_profile;

        --simulam durata unui select count in tabelul/tabelele aferente modulului A
        dbms_lock.sleep(2);

        FOR i in 1..5 loop
                insert into webapp.user_notifications_old
                (id_profile, module_name, module_aggregate_id)
                values
                    (p_id_profile, 'MODUL_C', 1);
            end loop;

    END verificare_mesaje;
END;
/

CREATE OR REPLACE PACKAGE WEBAPP.MESAJE_MODUL_D IS
    PROCEDURE verificare_mesaje (p_id_profile IN VARCHAR2);
END;
/
CREATE OR REPLACE PACKAGE BODY WEBAPP.MESAJE_MODUL_D IS
    PROCEDURE verificare_mesaje (p_id_profile IN VARCHAR2) IS
    BEGIN

        delete webapp.user_notifications_old t
        where t.module_name = 'MODUL_D' and
            t.id_profile = p_id_profile;

        --simulam durata unui select count in tabelul/tabelele aferente modulului A
        dbms_lock.sleep(8);

        FOR i in 1..20 loop
                insert into webapp.user_notifications_old
                (id_profile, module_name, module_aggregate_id)
                values
                    (p_id_profile, 'MODUL_D', 1);
            end loop;

    END verificare_mesaje;
END;
/