-- Initial schema setup
-- This script contains the initial database schema setup including the context package
create user webapp identified by parola01;
grant create session to webapp;

GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO webapp;
grant create any context to webapp;
GRANT UNLIMITED TABLESPACE TO webapp;
ALTER USER WEBAPP DEFAULT TABLESPACE USERS;

create or replace package webapp.DATABSE_CONNECTION_CONTEXT is
    procedure set_connection_context (p_username in varchar2);
end;
/
create or replace package body webapp.DATABSE_CONNECTION_CONTEXT is
    procedure set_connection_context (p_username in varchar2) is
    begin
        DBMS_SESSION.set_context(namespace => 'WEBAPP_CTX', attribute => 'USERNAME', value => p_username);
    end set_connection_context;
end;
/

CREATE CONTEXT WEBAPP_CTX USING webapp.DATABSE_CONNECTION_CONTEXT;
grant execute on Dbms_Session to webapp;
grant execute on webapp.DATABSE_CONNECTION_CONTEXT to webapp;

-- Create table
create table WEBAPP.USER_APP
(
    id          NUMBER generated by default on null as identity,
    username    VARCHAR2(255) not null,
    first_name  VARCHAR2(255) not null,
    last_name   VARCHAR2(255) not null,
    inserted_at TIMESTAMP(6) WITH TIME ZONE default SYSTIMESTAMP not null,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    version     NUMBER
)
    tablespace USERS
    pctfree 10
    initrans 1
    maxtrans 255;
-- Create/Recreate primary, unique and foreign key constraints
alter table WEBAPP.USER_APP
    add constraint PK_USERS primary key (ID)
        using index
            tablespace USERS
            pctfree 10
            initrans 2
            maxtrans 255;
alter table WEBAPP.USER_APP
    add unique (USERNAME)
        using index
            tablespace USERS
            pctfree 10
            initrans 2
            maxtrans 255;

-- Create table
create table WEBAPP.USER_PROFILES
(
    id           NUMBER generated by default on null as identity,
    id_user      NUMBER not null,
    profile_name VARCHAR2(255) not null,
    inserted_at  TIMESTAMP(6) WITH TIME ZONE default SYSTIMESTAMP not null,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    version      NUMBER
)
    tablespace USERS
    pctfree 10
    initrans 1
    maxtrans 255;
-- Create/Recreate indexes
create index WEBAPP.IDX_USER_PROFILES_USER on WEBAPP.USER_PROFILES (ID_USER)
    tablespace USERS
    pctfree 10
    initrans 2
    maxtrans 255;
-- Create/Recreate primary, unique and foreign key constraints
alter table WEBAPP.USER_PROFILES
    add constraint PK_USER_PROFILES primary key (ID)
        using index
            tablespace USERS
            pctfree 10
            initrans 2
            maxtrans 255;
alter table WEBAPP.USER_PROFILES
    add constraint FK_USER_PROFILES_USER foreign key (ID_USER)
        references WEBAPP.USER_APP (ID);

-- Adăugarea unei constrângeri de cheie primară pentru coloana ID
-- Create table
create table WEBAPP.USER_ACTIVE_PROFILES
(
    id           NUMBER generated by default on null as identity,
    id_user      NUMBER not null,
    username     VARCHAR2(255) not null,
    id_profile   NUMBER not null,
    profile_name VARCHAR2(255) not null,
    inserted_at  TIMESTAMP(6) WITH TIME ZONE default SYSTIMESTAMP not null,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    version      NUMBER
)
    tablespace USERS
    pctfree 10
    initrans 1
    maxtrans 255;
-- Create/Recreate primary, unique and foreign key constraints
alter table WEBAPP.USER_ACTIVE_PROFILES
    add constraint PK_USER_ACTIVE_PROFILES primary key (ID)
        using index
            tablespace USERS
            pctfree 10
            initrans 2
            maxtrans 255;


CREATE OR REPLACE TRIGGER webapp.trg_user_app_updated_at
    BEFORE UPDATE ON webapp.user_app
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER webapp.trg_user_profiles_updated_at
    BEFORE UPDATE ON webapp.user_profiles
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/